name: xHomes
version: '1.1'
main: org.curryman.xhomes.XHomes
commands:
  homes:
    description: Player command for the plugin
  home:
    description: Player command for plugin
  xhomes:
    description: Admin commands for the plugin
    permission: xhomes.admin

permissions:
  xhomes.use:
    description: Let players use basic commands
    default: not op
  xhomes.admin:
    description: Let players use admin commands
    default: op
  xhomes.homes.#:
    description: Lets players set a number of homes

softdepend:
  - HeadDatabase
